# Generated by Django 4.2.2 on 2023-10-23 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addTodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 12, 44, 18, 366303, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
    ]
