# Generated by Django 4.2.2 on 2023-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addTodo', '0002_alter_todo_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dates',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
