# Generated by Django 4.2.2 on 2023-10-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addTodo', '0003_alter_todo_dates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoModel',
        ),
    ]
